---
title: "Human Activity Recognition Dataset Cleaning"
author: "Jiachang (Ernest) Xu"
date: "6/20/2017"
output:
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Merges the training and the test sets to create one data set

```{r loading subject data, echo=TRUE}
## loading subject data
test_subject <- read.table("data/test/subject_test.txt", header = FALSE)
train_subject <- read.table("data/train/subject_train.txt", header = FALSE)
```

```{r loading features data, echo=TRUE}
## loading features data
test_features <- read.table("data/test/X_test.txt", header = FALSE)
train_features <- read.table("data/train/X_train.txt", header = FALSE)
```

```{r loading activity data, echo=TRUE}
## loading activity data
test_activity <- read.table("data/test/Y_test.txt" , header = FALSE)
train_activity <- read.table("data/train/Y_train.txt", header = FALSE)
```

```{r top rows of datasets, echo=TRUE}
## take a look at the top rows of datasets
head(test_subject)
head(train_subject)
head(test_features)
head(train_features)
head(test_activity)
head(train_activity)
```

```{r row combine, echo=TRUE}
subject <- rbind(train_subject, test_subject)
features <- rbind(train_features, test_features)
activity <- rbind(train_activity, test_activity)
head(subject)
head(features)
head(activity)
```

```{r factoring activity labels}
## factoring activity labels
labels <- read.table("data/activity_labels.txt", header = FALSE)
activity$V1 <- factor(activity$V1, levels = as.integer(labels$V1), labels = labels$V2)
```

```{r naming variables: subject & activity, echo=TRUE}
## naming variables: subject & activity
names(subject) <- c("subject")
names(activity) <- c("activity")
```

```{r naming variables: features, echo=TRUE}
## naming variables: features
features_variables <- read.table("data/features.txt", head=FALSE)
head(features_variables)
names(features)<- features_variables$V2
```

```{r subsetting features data, echo=TRUE}
## subsetting features data with mean and standard deviation
meanstdev <- c(as.character(features_variables$V2[grep("mean\\(\\)|std\\(\\)", features_variables$V2)]))
features_subdata <- subset(features, select = meanstdev)
```

```{r combining to a final data frame, echo=TRUE}
## combining subject, activity, and features data to a final data frame
subjectactivity <- cbind(subject, activity)
finaldata <- cbind(features_subdata, subjectactivity)
```

```{r explicitly naming time and frequency variables, echo=TRUE}
## explicitly naming time and frequency variables
names(finaldata) <- gsub("^t", "time", names(finaldata))
names(finaldata) <- gsub("^f", "frequency", names(finaldata))
```

```{r extracting means and standard deviation}
## extracting means and standard deviation
suppressWarnings(
    cleandata <- aggregate(finaldata, by = list(finaldata$subject, finaldata$activity), FUN = mean)
)
colnames(cleandata)[1] <- "Subject"
names(cleandata)[2] <- "Activity"
```

```{r writing to text file}
head(cleandata)
## writing clean data to text file
write.table(cleandata, file = "cleandata.txt", row.name = FALSE)
```
